<a href="https://colab.research.google.com/github/shahodi011/IT326-Project/blob/main/Reports/Phase2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Phase 1

# Project Goal

The goal of this project is to apply data mining techniques to classify patients by Alzheimer’s disease stage ,We aim to use clustering to group patients with similar traits and uncover hidden patterns.

# Dataset Source
The dataset was obtained from Kaggle:  
[Alzheimer’s Disease Dataset](https://www.kaggle.com/datasets/rabieelkharoua/alzheimers-disease-dataset)  

# Dataset Description

to retrieve the dataset info, we need to import it as follows :

In [ ]:
import pandas as pd
df = pd.read_csv("Raw_dataset.csv")

Now we can easily obtain the dataset info

Number and data types of attributes :

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
attribute_info = pd.DataFrame({
    'NameOfAttribute' : df.columns,
    'DataType' : df.dtypes.values
})
print(f"Attributes with their data types: \n")
print(attribute_info, "\n")

print("Number of attributes:", len(df.columns), "\n")

Attributes with their data types:

              NameOfAttribute DataType
0                   PatientID    int64
1                         Age    int64
2                      Gender    int64
3                   Ethnicity    int64
4              EducationLevel    int64
5                         BMI  float64
6                     Smoking    int64
7          AlcoholConsumption  float64
8            PhysicalActivity  float64
9                 DietQuality  float64
10               SleepQuality  float64
11    FamilyHistoryAlzheimers    int64
12      CardiovascularDisease    int64
13                   Diabetes    int64
14                 Depression    int64
15                 HeadInjury    int64
16               Hypertension    int64
17                 SystolicBP    int64
18                DiastolicBP    int64
19           CholesterolTotal  float64
20             CholesterolLDL  float64
21             CholesterolHDL  float64
22   CholesterolTriglycerides  float64
23                       MMSE  float64
24       FunctionalAssessment  float64
25           MemoryComplaints    int64
26         BehavioralProblems    int64
27                        ADL  float64
28                  Confusion    int64
29             Disorientation    int64
30         PersonalityChanges    int64
31  DifficultyCompletingTasks    int64
32              Forgetfulness    int64
33                  Diagnosis    int64
34             DoctorInCharge   object

Number of attributes: 35

Number of objects :

In [ ]:
print("Number of objects: ", len(df),"\n")

Number of objects:  2149

Class attribute information

In [ ]:
class_col = "Diagnosis"
print("Class attribute name: ", class_col, "\n")

Class attribute name:  Diagnosis

Show all unique values (labels)

In [ ]:
print("Possible values in the class attribute:",df[class_col].unique(), "\n")

Possible values in the class attribute: [0 1]

Show counts for each class

In [ ]:
print("Counts for each class in",df[class_col].value_counts())
print("")

Counts for each class in Diagnosis
0    1389
1     760
Name: count, dtype: int64

Sample of the raw dataset

In [ ]:
print("Sample of the raw dataset:")
print(df.head())

Sample of the raw dataset:
   PatientID  Age  Gender  Ethnicity  EducationLevel        BMI  Smoking  \
0       4751   73       0          0               2  22.927749        0
1       4752   89       0          0               0  26.827681        0
2       4753   73       0          3               1  17.795882        0
3       4754   74       1          0               1  33.800817        1
4       4755   89       0          0               0  20.716974        0

   AlcoholConsumption  PhysicalActivity  DietQuality  ...  MemoryComplaints  \
0           13.297218          6.327112     1.347214  ...                 0
1            4.542524          7.619885     0.518767  ...                 0
2           19.555085          7.844988     1.826335  ...                 0
3           12.209266          8.428001     7.435604  ...                 0
4           18.454356          6.310461     0.795498  ...                 0

   BehavioralProblems       ADL  Confusion  Disorientation  \
0                   0  1.725883          0               0
1                   0  2.592424          0               0
2                   0  7.119548          0               1
3                   1  6.481226          0               0
4                   0  0.014691          0               0

   PersonalityChanges  DifficultyCompletingTasks  Forgetfulness  Diagnosis  \
0                   0                          1              0          0
1                   0                          0              1          0
2                   0                          1              0          0
3                   0                          0              0          0
4                   1                          1              0          0

   DoctorInCharge
0       XXXConfid
1       XXXConfid
2       XXXConfid
3       XXXConfid
4       XXXConfid

[5 rows x 35 columns]

#  Phase 2

# Part 1 :Data Summarization

##1. Descriptive Statistics (Five-number Summary)
We report the five-number summary for numeric attributes: minimum, 25% (Q1), 50% (median,Q2), 75% (Q3), and maximum.

In [ ]:
df.describe()

,PatientID,Age,Gender,Ethnicity,EducationLevel,BMI,Smoking,AlcoholConsumption,PhysicalActivity,DietQuality,...,FunctionalAssessment,MemoryComplaints,BehavioralProblems,ADL,Confusion,Disorientation,PersonalityChanges,DifficultyCompletingTasks,Forgetfulness,Diagnosis
count,2149.000000,2149.000000,2149.000000,2149.000000,2149.000000,2149.000000,2149.000000,2149.000000,2149.000000,2149.000000,...,2149.000000,2149.000000,2149.000000,2149.000000,2149.000000,2149.000000,2149.000000,2149.000000,2149.000000,2149.000000
mean,5825.000000,74.908795,0.506282,0.697534,1.286645,27.655697,0.288506,10.039442,4.920202,4.993138,...,5.080055,0.208004,0.156817,4.982958,0.205212,0.158213,0.150768,0.158678,0.301536,0.353653
std,620.507185,8.990221,0.500077,0.996128,0.904527,7.217438,0.453173,5.757910,2.857191,2.909055,...,2.892743,0.405974,0.363713,2.949775,0.403950,0.365026,0.357906,0.365461,0.459032,0.478214
min,4751.000000,60.000000,0.000000,0.000000,0.000000,15.008851,0.000000,0.002003,0.003616,0.009385,...,0.000460,0.000000,0.000000,0.001288,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,5288.000000,67.000000,0.000000,0.000000,1.000000,21.611408,0.000000,5.139810,2.570626,2.458455,...,2.566281,0.000000,0.000000,2.342836,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,5825.000000,75.000000,1.000000,0.000000,1.000000,27.823924,0.000000,9.934412,4.766424,5.076087,...,5.094439,0.000000,0.000000,5.038973,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,6362.000000,83.000000,1.000000,1.000000,2.000000,33.869778,1.000000,15.157931,7.427899,7.558625,...,7.546981,0.000000,0.000000,7.581490,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000
max,6899.000000,90.000000,1.000000,3.000000,3.000000,39.992767,1.000000,19.989293,9.987429,9.998346,...,9.996467,1.000000,1.000000,9.999747,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

## 2.Missing Values
We show the number of missing values per column. Columns with missing values will be handled during preprocessing.

In [ ]:
df.isnull().sum()

PatientID                    0
Age                          0
Gender                       0
Ethnicity                    0
EducationLevel               0
BMI                          0
Smoking                      0
AlcoholConsumption           0
PhysicalActivity             0
DietQuality                  0
SleepQuality                 0
FamilyHistoryAlzheimers      0
CardiovascularDisease        0
Diabetes                     0
Depression                   0
HeadInjury                   0
Hypertension                 0
SystolicBP                   0
DiastolicBP                  0
CholesterolTotal             0
CholesterolLDL               0
CholesterolHDL               0
CholesterolTriglycerides     0
MMSE                         0
FunctionalAssessment         0
MemoryComplaints             0
BehavioralProblems           0
ADL                          0
Confusion                    0
Disorientation               0
PersonalityChanges           0
DifficultyCompletingTasks    0
Forgetfulness                0
Diagnosis                    0
DoctorInCharge               0
dtype: int64

##3. Class Label Distribution
We use Diagnosis as the class label. The counts below show the class distribution to consider later in modeling.

In [ ]:
TARGET_COL = "Diagnosis"
df[TARGET_COL].value_counts()

Diagnosis
0    1389
1     760
Name: count, dtype: int64